---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: auth
  name: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      imagePullSecrets:
        - name: gitea-registry
      containers:
        - name: users
          image: homelab/users
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: mongodb-shared-config
          env:
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "debug"
            - name: ADMIN_EMAIL
              value: "admin@homelab.local"
            - name: ADMIN_PASSWORD
              value: "admin123"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "jaeger.monitoring.svc:4317"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            requests:
              cpu: "25m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
