apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: auth
  name: users
  labels:
    release: kps
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: users
  namespaceSelector:
    matchNames:
      - auth
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
