---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: homelab

servers: 1
agents: 1

ports:
  - port: 5001:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 30000-30010:30000-30010
    nodeFilters:
      - loadbalancer

options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
