apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: finance
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: homelab/finance-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "debug"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "jaeger.monitoring.svc:4317"
          envFrom:
            - secretRef:
                name: mongodb-shared-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
