apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: auth
  name: gateway-home
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: auth-forward-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - gugagr.xyz
  rules:
    - host: gugagr.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  name: http
