apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: finance-api
build:
  artifacts:
    - image: homelab/finance-api
      context: ../../../../
      docker:
        dockerfile: apps/finance/services/api/Dockerfile
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl: {}
profiles:
  - name: local
    activation:
      - kubeContext: k3d-homelab
    build:
      local:
        push: false
  - name: ci
    build:
      local:
        push: true
      tagPolicy:
        gitCommit: {}
