name: auth-gateway

on:
  push:
    branches: [main]
    paths:
      - apps/auth/services/gateway/**
      - go.mod
      - go.sum
  pull_request:
    paths:
      - apps/auth/services/gateway/**
      - go.mod
      - go.sum

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test ./apps/auth/services/gateway/...
